[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
common = { version = "0.1.0", path = "../common" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
wasm-bindgen = "0.2.93"
yew = "0.21.0"
yew-router = "0.18.0"
